<script setup lang="ts">
import { nextTick, onMounted, reactive, ref } from "vue";
import { deletePost, getCachedAdminContent, normalizeSettings, refreshAdminContent, savePost, saveSettings, sortPosts, uploadAttachment, type AttachmentRecord, type BlogPostRecord, type ContentSettings } from "../content-api";

const MAX_SIZE = 100 * 1024 * 1024;
const editor = ref<HTMLElement>();
const fileInput = ref<HTMLInputElement>();
const posts = ref<BlogPostRecord[]>([]);
const currentId = ref<number | null>(null);
const settings = ref<ContentSettings>(normalizeSettings());
const hint = ref("正在读取文章...");
const form = reactive({ title: "", slug: "", status: "draft", date: "", summary: "" });
const today = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };
const escapeHtml = (value: unknown) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
const feedback = (message: string, variant = "info") => window.GellowFeedback?.showToast(message, "System Notice", variant);
const emptyPost = (): BlogPostRecord => ({ id: null, title: "Untitled Draft", slug: "new-post-slug", status: "draft", summary: "", content: "", publishedAt: today(), updatedAt: "" });
function selectedId() { const params = new URLSearchParams(location.search); if (params.get("mode") === "new") return null; const id = Number(params.get("id")); return Number.isFinite(id) ? id : null; }
function editorHtml(content: string) { if (!content.trim()) return ""; if (/<\/?[a-z][\s\S]*>/i.test(content)) return content; return content.split(/\n{2,}/).map((p) => `<p>${escapeHtml(p).replaceAll("\n", "<br />")}</p>`).join(""); }
function fill(post: BlogPostRecord) { currentId.value = post.id; form.title = post.title || ""; form.slug = post.slug || ""; form.status = post.status || "draft"; form.date = post.publishedAt || today(); form.summary = post.summary || ""; if (editor.value) editor.value.innerHTML = editorHtml(post.content || ""); document.title = `${post.title || "New Post"} | Gellow Post Editor`; }
function currentPost() { return posts.value.find((post) => post.id === currentId.value); }
function focusInside(node?: Node | null) { if (!editor.value) return; editor.value.focus(); const range = document.createRange(); if (node) range.selectNodeContents(node); else range.selectNodeContents(editor.value); range.collapse(false); const selection = getSelection(); selection?.removeAllRanges(); selection?.addRange(range); }
function insert(html: string, placeInside = true) { if (!editor.value) return; const template = document.createElement("template"); template.innerHTML = html.trim(); const first = [...template.content.childNodes].find((node) => node.nodeType === Node.ELEMENT_NODE); const selection = getSelection(); const range = selection?.rangeCount ? selection.getRangeAt(0) : null; const element = range?.startContainer.nodeType === Node.ELEMENT_NODE ? range.startContainer as Element : range?.startContainer.parentElement; const block = element?.closest("p, h1, h2, h3, ul, ol, blockquote, figure, hr"); if (block?.parentNode === editor.value) block.after(template.content); else editor.value.append(template.content); focusInside(placeInside ? first : null); }
function normalizeUrl(value: string) { try { const url = new URL(value.trim()); if (url.hostname.includes("youtube.com") && url.searchParams.get("v")) return `https://www.youtube.com/embed/${url.searchParams.get("v")}`; if (url.hostname === "youtu.be") return `https://www.youtube.com/embed/${url.pathname.replaceAll("/", "")}`; return url.toString(); } catch { return value.trim(); } }
function mediaByUrl(raw: string) { const url = normalizeUrl(raw); if (!url) return; if (/\.(png|jpe?g|gif|webp|svg|avif)(\?.*)?$/i.test(url)) insert(`<figure><img src="${escapeHtml(url)}" alt="Image" /></figure>`, false); else if (/\.(mp4|webm|ogg|mov|m4v)(\?.*)?$/i.test(url)) insert(`<figure><video controls preload="metadata" src="${escapeHtml(url)}"></video></figure>`, false); else if (/youtube\.com|youtu\.be|bilibili\.com/i.test(url)) insert(`<figure><iframe src="${escapeHtml(url)}" loading="lazy" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe></figure>`, false); else insert(`<p><a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(url)}</a></p>`); }
function fileSize(bytes: number) { return bytes < 1024 ? `${bytes} B` : bytes < 1048576 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1048576).toFixed(1)} MB`; }
function badge(file: AttachmentRecord) { const ext = file.filename.includes(".") ? file.filename.split(".").pop()?.toUpperCase() : ""; return ext?.slice(0, 4) || ({ audio: "MP3", pdf: "PDF", office: "DOC", video: "VID", image: "IMG", file: "FILE" }[file.kind]); }
function insertAttachment(file: AttachmentRecord) { if (file.kind === "image") { insert(`<figure class="attachment-block attachment-block-media" data-attachment-id="${escapeHtml(file.id)}"><img src="${escapeHtml(file.url)}" alt="${escapeHtml(file.filename)}" /><figcaption>${escapeHtml(file.filename)}</figcaption></figure>`, false); return; } if (file.kind === "video") { insert(`<figure class="attachment-block attachment-block-media" data-attachment-id="${escapeHtml(file.id)}"><video controls preload="metadata" src="${escapeHtml(file.url)}"></video><figcaption>${escapeHtml(file.filename)}</figcaption></figure>`, false); return; } const preview = file.kind === "audio" ? `<div class="attachment-preview" hidden><audio controls preload="metadata" src="${escapeHtml(file.url)}"></audio></div>` : ""; insert(`<figure class="attachment-block attachment-block-file" contenteditable="false"><button class="attachment-card" type="button" data-attachment-action="${file.kind === "audio" ? "preview" : "open"}" data-attachment-url="${escapeHtml(file.url)}" data-file-kind="${file.kind}" aria-expanded="false"><span class="attachment-icon">${badge(file)}</span><span class="attachment-body"><span class="attachment-name">${escapeHtml(file.filename)}</span><span class="attachment-meta">${fileSize(file.size)}</span></span></button>${preview}</figure>`, false); }
async function uploadFiles(files: File[]) { try { for (const file of files) { if (file.size > MAX_SIZE) throw new Error(`文件 ${file.name} 过大，当前单文件上限为 100 MB`); insertAttachment((await uploadAttachment(file)).attachment); } hint.value = "附件已插入正文。"; feedback("Files Uploaded", "success"); } catch (reason) { hint.value = `插入失败：${reason instanceof Error ? reason.message : "unknown error"}`; feedback("File Upload Failed", "error"); } }
function toolbar(action: string) { if (action === "paragraph") insert("<p>New paragraph</p>"); else if (action === "heading") insert("<h2>Section Title</h2>"); else if (action === "quote") insert("<blockquote>Quote</blockquote>"); else if (action === "list") insert("<ul><li>List item</li><li>List item</li></ul>"); else if (action === "divider") insert("<hr />", false); else if (action === "file") fileInput.value?.click(); else if (action === "link") { const url = prompt("Link URL"); if (url) { const text = prompt("Link Text", url) || url; insert(`<p><a href="${escapeHtml(normalizeUrl(url))}" target="_blank" rel="noopener noreferrer">${escapeHtml(text)}</a></p>`); } } else if (action === "image") { const url = prompt("Image URL"); if (url) { const caption = prompt("Caption (optional)", "") || ""; insert(`<figure><img src="${escapeHtml(url)}" alt="${escapeHtml(caption || "Image")}" />${caption ? `<figcaption>${escapeHtml(caption)}</figcaption>` : ""}</figure>`, false); } } else if (action === "video") { const url = prompt("Video URL"); if (url) mediaByUrl(url); } else if (action === "html") { const html = prompt("HTML Snippet"); if (html) insert(html, false); } }
async function persistSettings() { settings.value = normalizeSettings((await saveSettings(settings.value)).settings); }
async function save() { const previous = currentPost(); try { const payload: BlogPostRecord = { id: currentId.value, title: form.title.trim() || "未命名草稿", slug: form.slug.trim() || "new-post-slug", status: form.status, publishedAt: form.date || today(), summary: form.summary, content: editor.value?.innerHTML || "" }; const saved = (await savePost(payload)).post; if (previous && previous.slug !== saved.slug) { settings.value.featured_latest = settings.value.featured_latest.map((slug) => slug === previous.slug ? saved.slug : slug); settings.value.featured_home = settings.value.featured_home.map((slug) => slug === previous.slug ? saved.slug : slug); } posts.value = sortPosts([saved, ...posts.value.filter((post) => post.id !== saved.id)]); fill(saved); await persistSettings(); history.replaceState({}, "", `/notes/editor.html?id=${saved.id}`); hint.value = "文章已保存。"; feedback("Post Saved", "success"); } catch (reason) { hint.value = `保存失败：${reason instanceof Error ? reason.message : "unknown error"}`; feedback("Post Save Failed", "error"); } }
async function remove() { const post = currentPost(); if (!post?.id) { hint.value = "当前是新文章草稿，无需删除。"; feedback("No Saved Post", "error"); return; } try { await deletePost(post.id); settings.value.featured_latest = settings.value.featured_latest.filter((slug) => slug !== post.slug); settings.value.featured_home = settings.value.featured_home.filter((slug) => slug !== post.slug); await persistSettings(); feedback("Post Deleted", "success"); location.href = "/notes/"; } catch (reason) { hint.value = `删除失败：${reason instanceof Error ? reason.message : "unknown error"}`; feedback("Post Delete Failed", "error"); } }
function editorClick(event: MouseEvent) { const card = (event.target as Element).closest<HTMLElement>("[data-attachment-action]"); if (!card) return; event.preventDefault(); if (card.dataset.attachmentAction === "open") { if (card.dataset.attachmentUrl) window.open(card.dataset.attachmentUrl, "_blank", "noopener,noreferrer"); return; } const preview = card.closest(".attachment-block")?.querySelector<HTMLElement>(".attachment-preview"); if (preview) { const open = preview.hidden; preview.hidden = !open; card.setAttribute("aria-expanded", String(open)); card.closest(".attachment-block")?.classList.toggle("is-preview-open", open); } }
async function drop(event: DragEvent) { event.preventDefault(); editor.value?.classList.remove("is-dragover"); const files = [...(event.dataTransfer?.files || [])]; if (files.length) return uploadFiles(files); const uri = event.dataTransfer?.getData("text/uri-list")?.trim().split("\n")[0]; const text = event.dataTransfer?.getData("text/plain") || ""; if (uri || /^https?:\/\//i.test(text.trim())) mediaByUrl(uri || text.trim()); else if (text.trim()) insert(text.replace(/\r\n/g, "\n").split(/\n{2,}/).map((part) => `<p>${escapeHtml(part).replaceAll("\n", "<br />")}</p>`).join("")); hint.value = "拖入内容已插入正文。"; }
async function paste(event: ClipboardEvent) { const files = [...(event.clipboardData?.files || [])]; if (files.length) { event.preventDefault(); await uploadFiles(files); } }
onMounted(async () => { await nextTick(); document.title = "Gellow Post Editor"; const cached = getCachedAdminContent(); if (cached) { posts.value = sortPosts(cached.posts || []); settings.value = normalizeSettings(cached.settings); fill(posts.value.find((post) => post.id === selectedId()) || emptyPost()); hint.value = currentId.value ? "缓存文章已载入。" : "缓存草稿已载入。"; } try { const payload = await refreshAdminContent(); posts.value = sortPosts(payload.posts || []); settings.value = normalizeSettings(payload.settings); fill(posts.value.find((post) => post.id === selectedId()) || emptyPost()); hint.value = currentId.value ? "文章已载入。" : "新文章草稿已就绪。"; } catch (reason) { if (!cached) fill(emptyPost()); hint.value = `加载失败：${reason instanceof Error ? reason.message : "network request failed"}`; } });
</script>

<template>
  <header class="notes-minibar"><div class="wrap notes-minibar-inner"><a class="btn btn-notes-hub" href="/notes/">Back To Notes</a></div></header>
  <main class="wrap editor-page-shell"><div class="editor-layout">
    <aside class="editor-meta pixel"><div class="notes-panel-kicker">Post Editor</div><h1 class="section-title yellow">Edit Post</h1><form class="editor-meta-form" @submit.prevent="save">
      <label class="notes-field"><span>Title</span><input v-model="form.title" maxlength="120" required /></label><label class="notes-field"><span>Slug</span><input v-model="form.slug" maxlength="120" required /></label><label class="notes-field"><span>Status</span><select v-model="form.status"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label class="notes-field"><span>Date</span><input v-model="form.date" type="date" required /></label><label class="notes-field"><span>Summary</span><textarea v-model="form.summary" rows="7" maxlength="240"></textarea></label>
      <div class="editor-savebar"><p class="notes-hint">{{ hint }}</p><div class="meta-actions"><button class="btn btn-yellow" type="submit">Save</button><button class="btn btn-red" type="button" @click="remove">Delete</button><a class="btn btn-green" href="/notes/editor.html?mode=new">New Post</a></div></div>
    </form></aside>
    <section class="editor-workspace pixel"><div class="editor-workspace-head"><div><div class="notes-panel-kicker">Content Stage</div><h2 class="section-title pink">Content</h2></div><div class="editor-toolbar"><button v-for="action in ['paragraph','heading','quote','list','image','video','file','link','divider','html']" :key="action" class="tool-button" type="button" @click="toolbar(action)">{{ action[0].toUpperCase() + action.slice(1) }}</button></div></div>
      <div class="editor-canvas-shell"><div ref="editor" class="rich-editor" contenteditable="true" spellcheck="true" data-placeholder="在这里编辑正文。可以保留空行、插入图片、视频、链接或自定义 HTML。" @click="editorClick" @dragenter.prevent="editor?.classList.add('is-dragover')" @dragover.prevent @dragleave="editor?.classList.remove('is-dragover')" @drop="drop" @paste="paste"></div><input ref="fileInput" type="file" multiple hidden @change="uploadFiles([...($event.target as HTMLInputElement).files || []]); ($event.target as HTMLInputElement).value = ''" /></div>
    </section>
  </div></main>
</template>
